### ISSUE TITLE
How to install from source?

### ISSUE THREAD

**Issue by jethrokuan** [svenstaro/rofi-calc#10]
Hi, sorry for the noob question. I'm trying to install this using Nix, and have followed your install instructions. i'm now able to successfully compile it to obtain `calc.la` and `calc.so`, but how do I use these files in rofi?

**Comment by svenstaro** [comment]
You've got to figure out where your system's rofi is configured to look for plugins and then drop that there. For me, the location is `/usr/lib/rofi/calc.so` on Arch Linux.

**Comment by jethrokuan** [comment]
I see, thanks! It's not so straightforward with Nix, most of the already packaged plugins are scripts rather than C plugins, so I don't really have an example to follow.
