### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by Georacer** [svenstaro/rofi-calc#11]
Hello, 
I'm having issues trying to install. Couldn't find a better place to ask, so here goes:

OS: Ubuntu 18.04.1 LTS
rofi version:                  Version: 1.5.0 (installed from apt)
      Configuration file: /home/george/.config/rofi/config (not created by default, does not exist)

Installation steps:
```bash
>>cd <installation_dir_under_usr_home>
>>git clone <this repo url>
```
Then:
```bash
>>autoreconf -i
aclocal: warning: couldn't open directory 'm4': No such file or directory
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:32: installing './ar-lib'
configure.ac:17: installing './compile'
configure.ac:53: installing './config.guess'
configure.ac:53: installing './config.sub'
configure.ac:11: installing './install-sh'
configure.ac:11: installing './missing'
Makefile.am: installing './depcomp'
```
```bash
>>mkdir build
>>cd ./build
```
Finally this fails:
```bash
>>../configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for ar... ar
checking the archiver (ar) interface... ar
../configure: line 4734: PKG_PROG_PKG_CONFIG: command not found
../configure: line 4737: syntax error near unexpected token `glib,'
../configure: line 4737: `PKG_CHECK_MODULES(glib,     glib-2.0 >= 2.40 gio-unix-2.0 gmodule-2.0 )'
```

Launching according to the [man page instructions](http://manpages.ubuntu.com/manpages/bionic/man1/rofi.1.html):
> Use qalc to get a simple calculator in rofi:

            rofi -show calc -modi "calc:qalc +u8 -nocurrencies"

does not work either: it fails with
```
failed to execute: 'qalc +8 -nocurrencies'
Error: 'Failed to execute child process "qalc" (No such file or directory)'
```

Any suggestions? Thanks in advance.

**Comment by svenstaro** [comment]
You do not appear to have pkgconfig installed. Can you check that?

**Comment by svenstaro** [comment]
That's really weird. See [here](https://github.com/troglobit/inadyn/issues/142) for instance, where that exact error is thrown if it's not installed. Did you mess with your $PATH somehow? What's the output of `which pkg-config`?

**Comment by Georacer** [comment]
I didn't mess with my $PATH, at least not explicitly or knowingly.

```bash
:~$ which pkg-config
/usr/bin/pkg-config
:~$ ls -al /usr/bin/pkg-config 
-rwxr-xr-x 2 root root 51296 Απρ  21  2017 /usr/bin/pkg-config
```
Does this look right?

**Comment by svenstaro** [comment]
In that case that's an issue with how ubuntu installs rofi I'm afraid. Perhaps they're not properly installing the rofi pkg-config files.

**Comment by GladOSkar** [comment]
@zachkont I had the same issue. The `pkg-config`-files (`*.pc`) and development headers are only included with the associated `-dev` package.

Ubuntu uses the `-dev` suffix, some other distros use `-devel` or something else.

So if you are on Ubuntu just do `sudo apt install rofi-dev`. (also `libqalculate-dev`)

@svenstaro maybe this should be mentioned in the installation instructions

**Comment by svenstaro** [comment]
Could you make a PR that updates the instructions to help with Ubuntu?

**Comment by GladOSkar** [comment]
@svenstaro sure

@Georacer Re original issue: did you look at solutions that are not specific to this project? See:

- [https://askubuntu.com/questions/468661/how-to-fix-pkg-prog-pkg-config-command-not-found-error]
- [https://stackoverflow.com/questions/17089858/pkg-config-pkg-prog-pkg-config-command-not-found]

**Comment by Georacer** [comment]
I installed `libqalculate-dev` and now `make` and `install` finished (had already installed `rofi-dev`).
`install` required sudo to create the plugin files in `/usr/local/lib/rofi`.
Ran `./libtool --finish /usr/local/lib/rofi` from within `build`.

`rofi -show calc -modi calc -no-show-match -no-sort` did not work out of the box:
```bash
Mode calc is not found.
```

This worked:
```bash
rofi -plugin-path /usr/local/lib/rofi -show calc -modi calc -no-show-match -no-sort
```
![rofi-2018-10-05-1406-00000](https://user-images.githubusercontent.com/3149996/46531995-ef9df400-c8a7-11e8-8f7a-0ef97314d942.png)

However, any keystroke results in an immediate core dump:
```bash
** (process:9002): ERROR **: 14:03:52.573: Spawning child failed: Failed to execute child process “/usr/bin/qalc” (No such file or directory)
Trace/breakpoint trap (core dumped)
```

**Comment by Georacer** [comment]
`sudo apt-get install qalc` solves the qalc-not-found issue, but I don't think this is a desired step?

Additionally, the currency conversion doesn't seem to work:
![rofi-2018-10-05-1433-00000](https://user-images.githubusercontent.com/3149996/46532977-aa7bc100-c8ab-11e8-9e4b-5bb7ca0ab868.png)

**Comment by GladOSkar** [comment]
@Georacer OK the `qalc` binary should be included with the `qalc` package in ubuntu. Du you have that installed?

On my distro it comes with `libqalculate`...

**Comment by GladOSkar** [comment]
@Georacer turns out according to <https://packages.ubuntu.com/bionic/amd64/qalc/filelist> it is required, since only that ships the `qalc` binary.

On my distro, the `qalc` binary came with the `libqalculate` package.

So i guess i'll revisit the dependency instructions

**Comment by Georacer** [comment]
@GladOSkar 
Hey, I'm not complaining. I'm sure that `rofi-calc` is a neat tool, this is why I wanted to try it.

If Ubuntu 18.04 can't be fully supported, then it's not the end of the world ;) .

**Comment by GladOSkar** [comment]
Hey, not my project ^^ I just installed it yesterday and thought i could help :)

**Comment by Georacer** [comment]
After installing libqalculate from source as per that Github project instructions, rofi-calc now works with

'rofi -plugin-path /usr/local/lib/rofi -show calc -modi calc -no-show-match -no-sort'

**Comment by svenstaro** [comment]
If your distribution had an up-to-date qalculate it would just work but sadly many distributions ship very old software. Would you care to create a little guide in the README or wiki to set this up?

**Comment by Georacer** [comment]
I'm using an Ubuntu 18.04, so I'm not sure the repositories were the problem.

Do you really want me to add "Install libqalculate from source" in your README? That sounds like it would scare people away, instead of helping them.

**Comment by Georacer** [comment]
On the other hand:

`libqalculate6 is already the newest version (0.9.10-1).`

So, not so up-to-date after all...
:P

**Comment by svenstaro** [comment]
Could you add a wiki page with a link from the README to it?

**Comment by Georacer** [comment]
I can't.
For some reason clicking the Wiki button in your repo does nothing.
Do Pull Requests work for wikis as well?

**Comment by svenstaro** [comment]
Try now, it was restricted. :)

**Comment by svenstaro** [comment]
Thanks!

**Comment by Georacer** [comment]
Thank you for a nice rofi plugin!
