### ISSUE TITLE
ABI version does not match

### ISSUE THREAD

**Issue by alba4k** [svenstaro/rofi-calc#110]
![immagine](https://github.com/svenstaro/rofi-calc/assets/84153269/5ef10491-7bac-43b7-a5d2-b28dcc0f176b)

Only happens when using the latest rofi code, compiling it from source. not an issue in 1.7.5

**Comment by svenstaro** [comment]
Did you recompile rofi-calc against the rofi from source?

**Comment by alba4k** [comment]
@svenstaro Sorry for the delay, that worked. Should I open a different issue for the arch package, even though you don't have control over it?

**Comment by svenstaro** [comment]
Which Arch package? I maintain rofi-calc in Arch and it works quite well for me.

**Comment by alba4k** [comment]
oh only now I notice https://github.com/svenstaro/rofi-calc/issues/88 lmao

about the arch package, try building `rofi-git` and see if that has the issue
