### ISSUE TITLE
Issue with rofi-calc on wayland fork

### ISSUE THREAD

**Issue by papabryce** [svenstaro/rofi-calc#112]
When trying to run rofi-calc using the wayland fork of rofi I receive the error `Rofi-WARNING **: 17:16:40.239: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007`.

In addition, rofi will not launch when `calc` is added to the `modi` field in `config.rasi`. The error message I receive is `Mode calc is not found.`

Thank you

**Comment by svenstaro** [comment]
Did you make sure rofi-calc is compiled against that version of rofi you're running it against?

**Comment by papabryce** [comment]
I have not, I naively assumed I could install via my arch package manager. When I get a moment, I will build it from source and get back to you.

**Comment by lbonn** [comment]
See also https://github.com/lbonn/rofi/issues/96.

ABI compatibility between rofi and the wayland fork version is something that I unfortunately overlooked...

Right now, the tip of the wayland branch is compatible with the tip of the next branch in rofi AFAIK. But rofi 1.7.5 and 1.7.5+wayland2 are not compatible as the latter contains some extra commits from the next branch, as well as the bug mentioned above.

So you probably to recompile rofi-calc for now, sorry.

**Comment by svenstaro** [comment]
As far as I can tell, this is not a problem with rofi-calc in this repo. Closing.

**Comment by papabryce** [comment]
This was precisely the issue. I finally found the time to compile from source and everything is working properly. Thank you!
