### ISSUE TITLE
AUR package seems to be outdated 

### ISSUE THREAD

**Issue by niksingh710** [svenstaro/rofi-calc#113]
as the package on aur gives error on rofi wayland but compiled from git works fine.

**Comment by svenstaro** [comment]
What error do you get?

**Comment by niksingh710** [comment]
> What error do you get?

#107

**Comment by niksingh710** [comment]
> I can't support AUR packages. rofi and rofi-calc are available in Arch Linux through official channels. If there are problems with the AUR package, please talk to the author of the package in the comments.

Arch package seems to use release tags
ig it will be autofixed if you create a new tag with the new patch.
