### ISSUE TITLE
Found some very odd conversions, couldn't find any info about it online

### ISSUE THREAD

**Issue by m-hrstv** [svenstaro/rofi-calc#118]
So just a general question, i was trying to convert 28M seconds to days last night, and typed 'in' instead of 'to', and got a very curious and funny result - it tried(and succeeded, somehow!) to convert second-inch-days to kg/nPa. Works with all kinds of other conversions too, for instance you can convert meters to calories, somehow. Is that some sort of bug or is it intended and if so - what is the logic behind it? Thank you in advance.
![11](https://github.com/svenstaro/rofi-calc/assets/60304988/0c3b05c0-93ac-4bc0-8987-ab3b87770ab7)

**Comment by m-hrstv** [comment]
Alright, thank you, i'll have to look into it to satisfy my curiosity then :D

**Comment by svenstaro** [comment]
You can also always just use the command line tool `qalc`. It will give you exactly the same output as rofi. :)
