### ISSUE TITLE
Cannot start app

### ISSUE THREAD

**Issue by BbIXOD** [svenstaro/rofi-calc#119]
When I type `rofi -show calc -modi calc` i get
```
(process:33473): Rofi-WARNING **: 23:40:11.460: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007

(process:33473): View-WARNING **: 23:40:11.481: DPI auto-detect failed, the output is not known yet or does not provide a physical size
```
and then error that rofi doesn't know about calc.

**Comment by svenstaro** [comment]
Are you sure you built rofi-calc against the right version of rofi? I think you'll have to rebuild it with every update.

**Comment by BbIXOD** [comment]
Found what causes problem: https://github.com/NixOS/nixpkgs/issues/298539.

**Comment by FabricioLopees** [comment]
Try installing manually 

https://github.com/svenstaro/rofi-calc/wiki/Installing-libqalculate-from-source

**Comment by svenstaro** [comment]
At any rate, this is a distribution problem and not really anything I can do anything with from the source side.
