### ISSUE TITLE
calc & qalc in in combi-modi only works with older qalc version

### ISSUE THREAD

**Issue by johnwuelk** [svenstaro/rofi-calc#123]
I'm using rofi-calc with qalc in combi-modi, so that I can use history as I don't see it in the sole qalc:

`rofi -show calc -combi-modi "calc:qalc",calc -no-show-match -no-sort -calc-command "echo -n '{result}' | xclip"`

I found out that this does not work with a newer qalc version (5.1.1) as for example inputting an equation like 7 x = 21 would not display the value of x.
But in the older qalc version 3.22.0  it would show the value of x!

**Comment by svenstaro** [comment]
I never could get combi mode to work with this in an expected fashion. There are other issues about this here as well.

**Comment by svenstaro** [comment]
Should be fixed by #128.

**Comment by svenstaro** [comment]
@superpupervlad Seems to work well for me. rofi 2.0 is also not super recent. What's your distro and the error you're getting?
