### ISSUE TITLE
Can't see the full answer when writing an algebraic equation 

### ISSUE THREAD

**Issue by SasanK-0p** [svenstaro/rofi-calc#124]
Whenever I write any algebraic equation like
5x+9=2
It will just output -
(5*x)+9 =2 (something like this)

It's just the first line of output of qalc cli. It doesn't print the second line which has the actual value of x. Is there any way to fix it.

Sorry if asked something stupid

**Comment by mtpham99** [comment]
I am having the same issue. Right now I am using the "-terse" option to get it to display the results. However, this will also omit the input expression in the history.

**Comment by svenstaro** [comment]
I'm not sure there's a great way to fix this. You could always do `solve(5x+9=2)` which gives the answer on the same line but I see how that's less convenient.

**Comment by jdholtz** [comment]
@svenstaro would replacing the newlines in the qalc output with a separator (e.g. semicolon) work? So the qalc output would be:
```
((5 × x) − 2) = 1
x = 3/5 = 0.6
```
and the rofi-calc display would be `((5 × x) − 2) = 1; x = 3/5 = 0.6`

**Comment by svenstaro** [comment]
Hm that's actually smart, yeah. Wanna do a PR?

**Comment by jdholtz** [comment]
> Wanna do a PR?

Sure, I can do that.
