### ISSUE TITLE
Rofi-WARNING **: 17:48:50.327: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007

### ISSUE THREAD

**Issue by nnra6864** [svenstaro/rofi-calc#125]
### I should mention that I am using rofi-wayland, Arch.
```
rofi -show calc -modi calc -no-show-match -no-sort

(process:14927): Rofi-WARNING **: 17:48:50.327: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007
```
![image](https://github.com/user-attachments/assets/914a31f8-186a-4401-a5db-a35b928553af)

**Comment by svenstaro** [comment]
Did you see https://github.com/svenstaro/rofi-calc/issues/116?

**Comment by nnra6864** [comment]
> Did you see #116?

Hey, so sorry, I completely missed that one.
It'd be nice if there was a rofi-calc-wayland build in aur too(since wayland is becoming more and more popular) but that's asking for too much tbh.
Thanks for the solution!

**Comment by svenstaro** [comment]
Maybe the proper solution would be for rofi to support wayland natively. :)

**Comment by nnra6864** [comment]
> Maybe the proper solution would be for rofi to support wayland natively. :)

Indeed.
