### ISSUE TITLE
rofi sometimes does not terminate qalc process

### ISSUE THREAD

**Issue by MerlinTheProgramist** [svenstaro/rofi-calc#127]
I can't replicate it, but when I was using it to solve some complex limit, the output displayed something like: "press enter to cancel computation". But after closing it still remained as a background task and consumed my CPU

**Comment by svenstaro** [comment]
Would be great if you could find a way to easily repro this for me.

**Comment by svenstaro** [comment]
Still can't repro. Feel free to reopen if you have a good way for me to check this.
