### ISSUE TITLE
Install to wrong location on Ubuntu 18.10, /usr/local/lib/rofi/ instead of pkg-config rofi pluginsdir

### ISSUE THREAD

**Issue by sparr** [svenstaro/rofi-calc#15]
This is something of a dupe of #9 but hopefully with more info towards a solution.

When I follow the build instructions on Ubuntu 18.10 then `make install` ends up putting the build results in `/usr/local/lib/rofi/` instead of `pkg-config rofi --variable=pluginsdir` which is `/usr/lib/x86_64-linux-gnu/rofi/` for me.

As near as I can tell what happens is that `$ac_default_prefix` is `/usr/local` and that becomes `$prefix` which becomes `$exec_prefix` which gets '/lib' appended to make `$libdir` which gets '/rofi' appended to make '$plugindir'.

I'm not sure at what point this should be interrupted, but I'm told in freenode #rofi that the end result should be to use `pkg-config rofi --variable=pluginsdir` instead of the result of the above described process.

**Comment by svenstaro** [comment]
I have absolutely no automake skills so I copied from [here](https://github.com/marvinkreis/rofi-plugins/blob/master/rofi-prompt/configure.ac). Please try the latest commit.

**Comment by sparr** [comment]
check out #16
