### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jubalh** [svenstaro/rofi-calc#19]
Hi there,
I'm the maintainer of rofi in openSUSE. I saw that someone created a rofi-calc [package](https://build.opensuse.org/package/show/home%3Asiegel/rofi-calc) for openSUSE, but it only lives in the users home repository and building for Tumbleweed (rolling release) is also not enabled.

I would like to move rofi-calc into official openSUSE repos and support it for both Leap and Tumbleweed.
It seems that most changes since the last release are not very important ones but wanted to ping here anyway asking whether you consider creating a new release. So far the inofficial openSUSE package buliding from commit f24ac5e, and using releases might be nicer for official repos.

**Comment by svenstaro** [comment]
Ok, will cut a release soon.

**Comment by svenstaro** [comment]
There you go, a sweet signed tag v1.0.

**Comment by jubalh** [comment]
Awesome. Thanks!

**Comment by DaveDavenport** [comment]
Thanks for the release, neat to see rofi plugins packaged.
