### ISSUE TITLE
please make documentation slightly more clear

### ISSUE THREAD

**Issue by jaksco** [svenstaro/rofi-calc#2]
Can't wait to use this! 

I'm having a tiny bit of trouble compiling this. I'm using 1.5.1-13-git-1cd76989 version of rofi which I compiled from the rofi git on my fedora 28 machine. Rofi works great and it is installed into /usr/local/bin/rofi

I tried to run configure from the build sub-directory 

```
checking for glib... yes
checking for rofi... no
configure: error: Package requirements (rofi) were not met:

Package 'rofi', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables rofi_CFLAGS
and rofi_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Where do I put the rofi source code? right now it's in the directory above this one... This is my first time doing something like this

**Comment by svenstaro** [comment]
Mh sounds like pkg-config can't find your rofi. You've got to make sure that pkg-config is pointed to the rofi.pc in case it's not in standard paths.

**Comment by jaksco** [comment]
ohhh okay. finally figured it out 
`export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` 

then it worked. thanks
