### ISSUE TITLE
Thanks for this great plugin!

### ISSUE THREAD

**Issue by DaveDavenport** [svenstaro/rofi-calc#27]
It is very encouraging seeing people writing nice plugins for your software.

Thanks for all the effort! Please let me know if there are features you want to see in rofi to improve things.

R,

Dave

**Comment by svenstaro** [comment]
Thanks! Well, I'd have appreciated better history management inside of rofi but then again my use case might be too custom for putting it into the mainline rofi. The plugin isn't much code, take a look: https://github.com/svenstaro/rofi-calc/blob/master/src/calc.c
