### ISSUE TITLE
Support qalculate installed by snap

### ISSUE THREAD

**Issue by mnrce** [svenstaro/rofi-calc#29]
Hi, I'm using Ubuntu 16.04, I installed qalculate with snap using this command: `sudo snap install qalculate`.
The snap package provides the binary named `qalculate.qalc` instead of `qalc`, so rofi-calc failed to spawn the qalc process.
I tried to create a bash script named `qalc` in $PATH that starts `qalculate.qalc`. But because `qalculate.qalc` emits the error: `/snap/qalculate/133/bin/desktop-launch: line 29: /home/nghialm/.config/user-dirs.dirs: Permission denied`, `rofi-calc` just show me that error instead of the calculation result:

![image](https://user-images.githubusercontent.com/13317164/59867671-04c89d80-93b9-11e9-96bb-cf07010350a9.png)

**Comment by svenstaro** [comment]
I have no clue about snap. Any idea how this is _supposed_ to work?

**Comment by mnrce** [comment]
> I have no clue about snap. Any idea how this is _supposed_ to work?

It looks like _rofi-calc_  spawn a process: `qalc +u8 -s 'update_exchange_rates 1days' 1+1` and get the first line of output as result, is there anyway to make it get the last line of output as result instead? And fallback to `qalculate.qalc` if `qalc` doesn't exist?

![image](https://user-images.githubusercontent.com/13317164/59960331-35135780-94f1-11e9-9d6e-8a342739c01a.png)

**Comment by svenstaro** [comment]
Can you check whether that line is emitted on stderr or on stdout? If it's stderr then we could just ignore stderr.

**Comment by mnrce** [comment]
> Can you check whether that line is emitted on stderr or on stdout? If it's stderr then we could just ignore stderr.

Look like it's stderr:
![image](https://user-images.githubusercontent.com/13317164/59971492-2be4c200-95a7-11e9-9962-e0d4b6fe7ba2.png)

**Comment by svenstaro** [comment]
Considering this again, I think it makes sense to actually show `qalc` errors to the user. As for your case, it seems to be a legitimate permissions problem that you should be able to fix on your local system.

I added an option to master to allow your to specify the name of the qalc binary. Please test that and give me a shout.

**Comment by mnrce** [comment]
> As for your case, it seems to be a legitimate permissions problem that you should be able to fix on your local system.

Line 29 of the `desktop-launch` script doesn't even touch the `user-dirs.dirs` file. I even tried to `chmod 777 user-dirs.dirs` but it didn't work, either.
After googling for a day, I think it's an error of snap since a lot of apps get affected, and I can't find any solutions.

I think I might just remove the snap package and compile qalculate myself.

> I added an option to master to allow your to specify the name of the qalc binary. Please test that and give me a shout.

The option works fine.
