### ISSUE TITLE
Not working in combi mode

### ISSUE THREAD

**Issue by supermar1010** [svenstaro/rofi-calc#33]
Hi,
the plugin works for me if I launch rofi with the supplied command. But I want it to be available in combi mode. I tried adding it to the list of modes but it doesn't work. 
If I type something like 5*3 I get one entry saying "calc Add to history" but no result.
Do you know what the problem is?

My config file:
```
rofi.modi:                           combi

rofi.combi-modi:                     window,drun,ssh,calc
```

**Comment by svenstaro** [comment]
To be honest this is quite the abuse of rofi in general and I don't really expect it to work in combi mode. I tried before.

**Comment by DaveDavenport** [comment]
While it would be fun, I don't expect this to work in combi mode.

Maybe in the future we can discuss how to make this possible.

**Comment by supermar1010** [comment]
Ok thats unfortunate I hoped to be able to have a calculator integrated in my rofi :(
If you make it work you'd make my day :D if you need a tester feel free to tag me

**Comment by jeriewang** [comment]
This is definitely a hackish solution but I got this working. It's a bit inconvenient but probably better than nothing.

I can run `rofi -show combi -combi-modi calc:~/show_calc.sh,window,drun`, and inside my `~/show_calc.sh` I have
```sh
#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Show calculator"
    
else
    kill `pidof rofi` 
    # so rofi doesn't complain "can't launch rofi inside rofi"
    rofi -show calc
fi
```
So there's always a single entry that lets me go into the calculator mode.

**Comment by BillyCroan** [comment]
> To be honest this is quite the abuse of rofi in general and I don't really expect it to work in combi mode. I tried before.

I'm very new to rofi.  But.... as highly customizable as rofi is, why is this "abuse"?  If it can't combi, what's the point?  if one has to give up all app selection to gain calc functionality why use rofi at all?

If you have to "chainload" a rofi in calcmode from a rofi in combi as @mia1024 suggested then you might as well chainload gnome-calculator right?

**Comment by DaveDavenport** [comment]
you can open multiple modes in rofi and switch between them within rofi.. No need to 'chainload' anything.

**Comment by DaveDavenport** [comment]
Things are what they are.  There is a technical reason why things work they way they currently work. 
As stated above, a discussion can be had on how to improve this:

> Maybe in the future we can discuss how to make this possible.

I tried to help by giving an alternative that **would** work in current version of rofi that would imho be better then daisy chaining. I see this was not appreciated.

Repeatedly pointing out that calc does not work in combi mode and how this is not as good as it could be is not very constructive given this was already acknowledged.

**Comment by DaveDavenport** [comment]
> I'm very new to rofi. But.... as highly customizable as rofi is, why is this "abuse"? If it can't combi, what's the point? if one has to give up all app selection to gain calc functionality why use rofi at all?
> 

If I remember correctly albert and ulauncher might be more suited for your use-case: https://albertlauncher.github.io/ / https://ulauncher.io/.
I thought it integrated launcher and calculator in that fashion.'

**Comment by Etsi0** [comment]
> This is definitely a hackish solution but I got this working. It's a bit inconvenient but probably better than nothing.
> 
> I can run `rofi -show combi -combi-modi calc:~/show_calc.sh,window,drun`, and inside my `~/show_calc.sh` I have
> 
> #!/bin/bash
> 
> if [[ -z "$1" ]]; then
>     echo "Show calculator"
>     
> else
>     kill `pidof rofi` 
>     # so rofi doesn't complain "can't launch rofi inside rofi"
>     rofi -show calc
> fi
> 
> So there's always a single entry that lets me go into the calculator mode.

thanks m8, this worked great
