### ISSUE TITLE
Delete items from the history

### ISSUE THREAD

**Issue by linwaytin** [svenstaro/rofi-calc#34]
Thanks for this amazing project.

I am wondering if there is a way to delete items from the history.
Sometime I wrongly add calculations I don't want into the history.
I know I can delete them in the file `.local/share/rofi/rofi_calc_history`,
but it would be great if I can delete them from the interface of Rofi.

Thank you.

**Comment by svenstaro** [comment]
Hm yeah sounds like a bug actually since SHIFT-DEL already removes items from the display but it doesn't remove them from history.

**Comment by linwaytin** [comment]
That's what I saw.

**Comment by svenstaro** [comment]
Please test and give me some feedback. I'll then make a release.

**Comment by linwaytin** [comment]
That works. Thank you.
