### ISSUE TITLE
Include 1,000 comma separator in output

### ISSUE THREAD

**Issue by stvsu** [svenstaro/rofi-calc#37]
Is it possible to implement an argument which will show `,` separators in the output? For instance: 500*12 = `6,000` rather than `6000`

This would help visualize the results much faster!

**Comment by stvsu** [comment]
Solved: 

This can be achieved by passing an argument to qalc: `qalc --set 'digit_grouping 2'` or by adding that argument to `~/.config/qalculate/qalc.cfg`

**Comment by svenstaro** [comment]
Could you make a PR to document this in the README?

**Comment by stvsu** [comment]
Done. Thanks for this awesome program

**Comment by jorgelaranjo** [comment]
Calling directly from the CLI
`rofi -show calc -modi calc -no-show-match -no-sort -no-persist-history -theme gruvbox-dark-hard`

![rofi-2022-10-16-1124-00000](https://user-images.githubusercontent.com/1196202/196030226-65324a8f-da48-4987-a99c-d9216e88bbb9.png)

and calling from i3wm config

`bindsym $mod+c exec "rofi -show calc -modi calc -no-show-match -no-sort -no-persist-history -theme gruvbox-dark-hard"`

![rofi-2022-10-16-1124-00001](https://user-images.githubusercontent.com/1196202/196030241-b8793e43-9265-425c-9c25-8f35537de432.png)


Wonder why does not show the separator...
