### ISSUE TITLE
crash on equals sign

### ISSUE THREAD

**Issue by jaksco** [svenstaro/rofi-calc#4]
I tried running `60x + 30 = 50` in rofi-calc and it closed rofi

```
xk@localhost ~/.config> rofi -show calc -modi calc -no-show-match -no-sort

** (process:732): ERROR **: 17:38:22.011: Process errored with: Child process killed by signal 6
fish: “rofi -show calc -modi calc -no-…” terminated by signal SIGTRAP (Trace or breakpoint trap)
```
if you'd like me to send more info, what's the way for me to do that?

**Comment by svenstaro** [comment]
Can't reproduce. The exact same scenario works perfectly for me. Maybe try uprading libqalculate? At any rate, try this in your console:

    qalc "60x + 30 = 50"

**Comment by jaksco** [comment]
ah yes. It appears to be a problem with qalc. I'll figure it out thanks
