### ISSUE TITLE
can not  build. 

### ISSUE THREAD

**Issue by hexdsl** [svenstaro/rofi-calc#41]
get following lines that i beleive to be errors 

     aclocal: warning: couldn't open directory 'm4': No such file or directory

and then at the end

     ../configure: line 4470: PKG_PROG_PKG_CONFIG: command not found
     ../configure: line 4473: syntax error near unexpected token `glib,'
     ../configure: line 4473: `PKG_CHECK_MODULES(glib,     glib-2.0 >= 2.40 gio-unix-2.0 gmodule-2.0 )'

Am on Arch (Updates done) have compiling does work for me on other things. Trying AUR package. also m4 and glib are all installed. 

thanks

**Comment by hexdsl** [comment]
rebooted.. now builds... no idea... sorry for posting

**Comment by svenstaro** [comment]
Er you're welcome :D
