### ISSUE TITLE
Cant save this to clipboard?

### ISSUE THREAD

**Issue by thepenguinthatwants** [svenstaro/rofi-calc#43]
Hi!

Thanks for doing such great calculator.

I've tried this with keybinding and also with running straight from commandline.

The outputs doenst seem to be saved when I press enter? Is there any way to debug this or maybe  am doing this wrong.

`bindsym XF86Calculator exec rofi -show calc -modi calc -no-show-match -no-sort -calc-command "echo '{result}' | xclip"`

For now I need to write the outputs to paper to remember them.

**Comment by joelostblom** [comment]
Pressing enter adds the entry to the rofi calc history. To trigger the `-calc-comand` you need to press control + enter or navigate to the entry in the history you want and press enter. That worked for me (using `xsel -b` instead of `xclip`, but that should not matter).

**Comment by svenstaro** [comment]
I added a note to the README about this which should make it more obvious how to do this.

**Comment by thepenguinthatwants** [comment]
Hi!
So I have those saved in the list but moving on the list and choosing by enter. 
I cant paste the output? It doesnt seem to save in my clipboard eventho its saved on the list.

**Comment by svenstaro** [comment]
Works for me but you have to use normal Return on the saved entries and Ctrl-Return on the current input to execute the clipboard command with the selected text. It does show up in my clipboard in both cases then.

**Comment by thepenguinthatwants** [comment]
I have both xsel and xclip installed.
Not sure if I can get more verbose output to see whats wrong.

**Comment by svenstaro** [comment]
If it helps, my exact command is `rofi -show calc -modi calc -no-show-match -no-sort -calc-command "echo '{result}' | xclip"`

**Comment by thepenguinthatwants** [comment]
Thanks for the command. It seems like maybe its on my part something is wrong. Cant get it work.

**Comment by kaistian** [comment]
@thepenguinthatwants what version of rofi and rofi-calc are you using?
I tried to build master branch against rofi 1.5.1 and with this combination `-calc-command "echo '{result}'"` did not work, I got following error
`rofi: symbol lookup error: /usr/lib/x86_64-linux-gnu/rofi/calc.so: undefined symbol: helper_string_replace_if_exists`
I upgraded to 1.5.4 and it did work.

@svenstaro Maybe update the README with `-n` to echo. Without `-n` echo will add a newline at the end with the result that enter is pressed after pasting.

**Comment by thepenguinthatwants** [comment]
@kaistian 
I am using rofi 1.5.4 version and rofi-calc 1.6-1 version downloaded from aur.

Just wondering if the way it adds to clipboard somehow doesnt work on my system.

**Comment by kaistian** [comment]
It's easy to find out if xclip work on you system, just run this command
`echo -n "Some text in clipboard" | xclip`
you should now be able to paste this text by clicking middle mouse button.

**Comment by svenstaro** [comment]
Seems we can consider this closed?

**Comment by thepenguinthatwants** [comment]
yeh seemingly my xclip is not working well then.

**Comment by elvizcacho** [comment]
You have to do it like this: 
```shell
rofi -show calc -modi calc -no-show-match -no-sort -calc-command "echo '{result}' | xclip -selection clipboard"
```
