### ISSUE TITLE
Allow definition of decimal separator

### ISSUE THREAD

**Issue by fdw** [svenstaro/rofi-calc#44]
First off, thanks for this amazing tool! I've been using it for years now and it works beautifully :)

What I would like to do is to use `.` as my decimal separator. Unfortunately, my locale is `de_DE`, which uses `,`. I couldn't find any way to change just this setting, neither in `rofi-calc` nor in `qalc` itself. Do you have an idea?

**Comment by svenstaro** [comment]
Glad you like it! I've added a note to the README that should fix your issue. Can you give it a spin?

**Comment by fdw** [comment]
Works like a charm, thank you very much!

**Comment by svenstaro** [comment]
Glad to hear it!
