### ISSUE TITLE
Segfault after start typing

### ISSUE THREAD

**Issue by nylocx** [svenstaro/rofi-calc#45]
Since this morning I noticed that rofi-calc is segfaulting the moment I start to type.

I'm on Arch linux and build rofi-calc from aur https://aur.archlinux.org/packages/rofi-calc/

I noticed that there was an update of [libqcalculate](https://www.archlinux.org/packages/?q=libqalculate)

Downgrading to libqalculate-3.8.0-1 resolves the segfault.

I wanted to check `/usr/lib/rofi/calc.so` with ldd to see which library is linked but I seems that libqcalculate is not in the listed.

If you need more info or some traces just let me know.

```bash
 !  ~  env LANG=C rofi -show calc -modi calc -no-show-match -no-sort                                                             1730ms  Mi 15 Apr 2020 08:58:59 CEST

** (process:50138): ERROR **: 08:59:18.909: Process errored with: Child process killed by signal 11
```

**Comment by svenstaro** [comment]
Did you try to rebuild it?

**Comment by nylocx** [comment]
Yeah that was the first thing I tried. But I have to admit that I use an AUR Helper for that but my pikaur -S rofi-calc --rebuild at least showed me the build output and stated that it will reinstall.

**Comment by nylocx** [comment]
I just did a bit digging in the code and it seems that this plugin is not linking against the libqalculate library but just uses the cli. I update again and check the binary qalc directly.

**Comment by aeriff** [comment]
I ran into the same issue and downgrading libqalculate also solved it. Tried rebuilding, etc. as suggested.

**Comment by aeriff** [comment]
This issue may be related: https://github.com/Qalculate/libqalculate/issues/184

Confirmed `rofi-calc` no longer segfaults with `libqalculate=3.9.0.a`.
