### ISSUE TITLE
Can't run latest qalculate with rofi-qalc on ubuntu 18.04

### ISSUE THREAD

**Issue by maxime-rey** [svenstaro/rofi-calc#47]
I am on ubuntu 18.04 and all computations I did were working except for currencies. I saw that this was due to a really outdated version of qalc so I removed it and used snap to install qalculate as advised on [qalculate](https://github.com/Qalculate/libqalculate).  
I did an alias for the qalc command to redirect it to /snap/bin/qalculate.qalc but this didn't work with rofi-calc. As soon as I typed anything rofi crashed with the following error message.
`** (process:31646): ERROR **: 14:55:30.654: Spawning child failed: Failed to execute child process “qalc” (No such file or directory)`  

Then, I found out that you mentioned this problem on your [wiki](https://github.com/svenstaro/rofi-calc/wiki/Installing-libqalculate-from-source) and tried to do `sudo ln -s /snap/bin/qalculate.qalc /usr/bin/qalc` as said but it did not work either, leaving rofi with the following message as soon as I typed anything.
`** (process:29771): ERROR **: 14:40:02.267: Process errored with: Child process exited with code 1`

Do you have any idea what I might have done wrong ?

**Comment by svenstaro** [comment]
I recommend against using snaps in this case and would advise you to do install a proper updated qalc package or update your Ubuntu. 18.04 is plenty old after all. Snaps come with a lot of weirdnesses. If you really wanna go that route, try flatpack instead.

**Comment by svenstaro** [comment]
You can try the official latest flatpack: https://github.com/Qalculate/libqalculate/releases/download/v3.10.0/qalculate-gtk-3.10.0-x86_64.flatpak

**Comment by maxime-rey** [comment]
Thank too for the info, I had weird experiences  with snap some time ago but totally forgot about it (didn't know it was "normal" behaviour). Concerning Ubuntu, I'll keep that in mind and update it in a bit then (looks like there's still some GUI problems so it seems wiser to wait).

In the end, as I don't really want to look into flatpack I used the [self-contained binaries](https://github.com/Qalculate/qalculate-gtk/releases/download/v3.10.0/qalculate-3.10.0-x86_64.tar.xz) from qalculate, put it somewhere, did a symbolic link as you said and it works like a charm now.

Thank you very much for your advices, help and for rofi-calc !

**Comment by svenstaro** [comment]
Glad it's working for you now! Enjoy.
