### ISSUE TITLE
How to install this plugin on Linux Mint?

### ISSUE THREAD

**Issue by ProgrammingLife** [svenstaro/rofi-calc#48]
I've done this step for Ubuntu:
`apt install rofi-dev qalc libqalculate-dev`
and then I try to run rofi:
```
rofi -show calc -modi calc -no-show-match -no-sort
Mode calc is not found.
The following modi are known:
        * window
        * windowcd
        * run
        * ssh
        * drun
        * combi
        * keys
```
How to install this plugin? What configs I should edit?

**Comment by svenstaro** [comment]
Well, did you follow the compile and install instructions in the README?

```
$ autoreconf -i
$ mkdir build
$ cd build/
$ ../configure
$ make
$ make install
```

**Comment by svenstaro** [comment]
I'll close this for the time being. If you need more help, feel free to request to reopen.
