### ISSUE TITLE
Bold results

### ISSUE THREAD

**Issue by p3lim** [svenstaro/rofi-calc#5]
Probably a theme issue, but any pointers on how to make the results not bold?
![](https://p3l.im/fe98)

**Comment by svenstaro** [comment]
That's indeed the case. I guess you could compile a version without that bold stuff or we could add a config and make it configurable.

**Comment by p3lim** [comment]
Configure option please.-------- Original Message --------Subject: Re: [svenstaro/rofi-calc] Bold results (#5)From: Sven-Hendrik Haase To: svenstaro/rofi-calc CC: Adrian L Lange ,Author That's indeed the case. I guess you could compile a version without that bold stuff or we could add a config and make it configurable.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/svenstaro/rofi-calc","title":"svenstaro/rofi-calc","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/svenstaro/rofi-calc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@svenstaro in #5: That's indeed the case. I guess you could compile a version without that bold stuff or we could add a config and make it configurable."}],"action":{"name":"View Issue","url":"https://github.com/svenstaro/rofi-calc/issues/5#issuecomment-408662087"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/svenstaro/rofi-calc/issues/5#issuecomment-408662087",
"url": "https://github.com/svenstaro/rofi-calc/issues/5#issuecomment-408662087",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [svenstaro/rofi-calc] Bold results (#5)",
"sections": [
{
"text": "",
"activityTitle": "**Sven-Hendrik Haase**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@svenstaro",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"svenstaro/rofi-calc\",\n\"issueId\": 5,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"svenstaro/rofi-calc\",\n\"issueId\": 5\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/svenstaro/rofi-calc/issues/5#issuecomment-408662087"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341622685\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by svenstaro** [comment]
In case anybody wants to add a quick option flag for this, I'll definitely merge it!
