### ISSUE TITLE
Installation instructions refer to libqalculate header files, but they are not used.

### ISSUE THREAD

**Issue by DaveDavenport** [svenstaro/rofi-calc#51]
The installation instructions in [README](https://github.com/svenstaro/rofi-calc/blob/master/README.md#installation) list

```
You will also need development headers for rofi and libqalculate. Depending on your distribution these may be included in different packages:
```

but when looking at C  code for header file inclusion, I don't  see it used: [here?](https://github.com/svenstaro/rofi-calc/blob/master/src/calc.c#L25). Same for  configure.ac.

As of 2020-06-22.

Might be good to update instructions?

**Comment by svenstaro** [comment]
Oh indeed, I don't even remember when I actually linked to libqalculate directly.
