### ISSUE TITLE
Error while saving to clipboard

### ISSUE THREAD

**Issue by UtkarshVerma** [svenstaro/rofi-calc#55]
I'm executing `rofi-calc` using:
```
rofi -modi calc -show calc -calc-command "echo '{result}' | xclip -r -selection clipboard"
```
`rofi` opens properly but when I enter '1 year to s' and press `Ctrl+Enter`, nothing is copied to clipboard. And the following is shown in the terminal.
```
zsh:1: unmatched "
```
Basic arithmetic like `12*10` etc are getting copied to clipboard but I can't get this to work.

**Comment by svenstaro** [comment]
Interesting. Can you show me the local output you get when you just use command line rofi with the same inputs on your system?

**Comment by UtkarshVerma** [comment]
I'm not sure what you mean by the local output, could you please elaborate a bit?

**Comment by UtkarshVerma** [comment]
I'm not sure what you mean by local output, could you please elaborate a bit?

**Comment by svenstaro** [comment]
Basically just launch `qalc` in a terminal twice, once for showing the output of a working expression and once for showing the broken expression. Since rofi-calc parses the stdout of `qalc`, this would make it easier to debug. Also, what's your `qalc

**Comment by UtkarshVerma** [comment]
I'm using `qalc v2.8.2`. This is what I got after running `qalc`:
```
$ qalc     
> 12*1

  12 * 1 = 12

> 1 year to s

  1 * year = 31557600 s

```

**Comment by Flurrywinde** [comment]
I am having the same issue. Qalc version is 3.15.0. Rofi version is 1.5.4. Rofi-calc freshly git cloned (last commit: fb455cb Nov 14, 2020)

Rofi command: `rofi -show calc -modi calc -no-show-match -no-sort -calc-command "echo -n '{result}' | xsel -b"`

My qalc output:
```
$ qalc "1+1"
1 + 1 = 2
$ qalc "1 year to s"
1 × year = 31557600 s
$ qalc btc
BTC ≈ $18795.80384
```
"1+1" worked while the other two did not. I believe this issue must be the × and ≈ aren't regular characters.

In #62 , @svenstaro says: "If you want to use this, you should go with -no-unicode for the time being as I really don't know how to detect the ≈ properly in C11. :P"

Adding -no-unicode fixed the issue for me.

Maybe the * in @UtkarshVerma 's case is somehow unicode too?

**Comment by svenstaro** [comment]
Closing this for the time being as we lack replies and information. Anyone experiencing this issue should add more information and request a reopen.

**Comment by FlySlime** [comment]
I found a workaround that keeps the Unicode characters :smile:. It will save the `{expression}` and `{result}` to your clipboard (which is what I want at least).

`COPY=/tmp/rofiCopy
rofi -show calc -modi calc -no-show-match -no-sort >$COPY
echo -n $(cat $COPY) | xclip -selection clipboard `
