### ISSUE TITLE
Unicode operators

### ISSUE THREAD

**Issue by skalyan91** [svenstaro/rofi-calc#57]
I’m not able to get Unicode operators (× and ÷) to display in rofi (I just see * and /), even though they’re displayed in the terminal. I have the relevant options enabled in `~/.config/qalculate/qalc.cfg`, and I know that the configuration file is being loaded, because I’m able to change the thousands separator. It just doesn’t work for Unicode operators.

**Comment by svenstaro** [comment]
Well, I just tried this real quick and I apparently everything just works if we enable Unicode support without any other code changes so I'll just do that.

**Comment by svenstaro** [comment]
Ok, try master real quick please, if it's good for you, I'll just make a release.

**Comment by svenstaro** [comment]
Eh, I just made a new release and put it into Arch. Enjoy!

**Comment by skalyan91** [comment]
Thanks! Will try it later today (I’m not at my Linux computer right now).

**Comment by skalyan91** [comment]
@svenstaro It works perfectly! Thank you!

**Comment by svenstaro** [comment]
Glad to hear, have fun!
