### ISSUE TITLE
History wiped on every run

### ISSUE THREAD

**Issue by p3lim** [svenstaro/rofi-calc#6]
Would like to see the history being kept between "sessions", and a keybind to remove lines.
Nice if I want to store a list of typical currency conversions.

**Comment by svenstaro** [comment]
Would you expect the old results to persist or would you expect the results to be recalculated (and as such expect for currency conversions to be refetched)?

**Comment by p3lim** [comment]
I'm not expecting results to be recalculated, but that would be a really cool feature!

**Comment by csholmq** [comment]
Persistent history would be awesome. No re-calculation unless you re-run the calc IMO.

Not able to copy {result} to xclip for some reason so having to memorize the result before pressing Esc is kind of bulky.

**Comment by svenstaro** [comment]
I'll take add this soon.

**Comment by svenstaro** [comment]
Ok, it's implemented. Enjoy.

**Comment by DaveDavenport** [comment]
Could you have used rofi's history system for this? 
https://github.com/davatorium/rofi/blob/next/include/history.h

(The frequency sorting  might not be desirable, dunno).

**Comment by svenstaro** [comment]
Honestly I didn't know about it but if it sorts it's no good.

**Comment by maximbaz** [comment]
@svenstaro FYI there are some issues with this feature, just after the upgrade `rofi` would crash when adding something to history:

```
❯ rofi -show calc -modi calc -no-show-match -no-sort -terse                                                             
** (process:25970): ERROR **: 16:15:35.523: Error while writing the history file: Failed to create file “/home/maximbaz/.local/share/rofi/rofi_calc_history.6AMG0Z”: No such file or directory
[1]    25970 trace trap (core dumped)  rofi -show calc -modi calc -no-show-match -no-sort -terse
```

Manual mitigation steps don't entirely solve the issue, it still crashes on the first attempt:

```
❯ mkdir -p /home/maximbaz/.local/share/rofi

❯ rofi -show calc -modi calc -no-show-match -no-sort -terse
free(): invalid pointer
[1]    26414 abort (core dumped)  rofi -show calc -modi calc -no-show-match -no-sort -terse
```

Although the history is saved:

```
❯ cat /home/maximbaz/.local/share/rofi/rofi_calc_history               
$10
```

And on the second run everything is fine, I see `$10` in the history and I can add more stuff to the history without any crash. 

If I `rm /home/maximbaz/.local/share/rofi/rofi_calc_history`, the crash will re-occur on the first run.

**Comment by svenstaro** [comment]
Oh no. Will take a look.

**Comment by svenstaro** [comment]
Fixed, please check.

**Comment by csholmq** [comment]
Did you commit or is it only in the release zip file?

**Comment by svenstaro** [comment]
It's tag v1.5 (commit 53a18d6).

**Comment by csholmq** [comment]
That's so strange. I looked for it but the only commit I found was 19h old. I'm blaming cache 🙂

Thanks. Will test asap.

**Comment by maximbaz** [comment]
Works well, good job @svenstaro 👍

**Comment by svenstaro** [comment]
Cool, enjoy!
