### ISSUE TITLE
How to change default currency?

### ISSUE THREAD

**Issue by gusbemacbe** [svenstaro/rofi-calc#60]
Hello,

When I run the command `100 USD`, it output euros instead of Brazilian currency. I tried to run `LC_NUMERIC=pt_PT.UTF-8 rofi -show calc -modi calc -no-show-match -no-sort`, but no luck.

**Comment by svenstaro** [comment]
Hi, try

    LC_MONETARY=pt_PT.UTF-8 rofi -show calc -modi calc -no-show-match -no-sort

**Comment by gusbemacbe** [comment]
> LC_MONETARY=pt_PT.UTF-8 rofi -show calc -modi calc -no-show-match -no-sort

It still shows € instead of BRL.

**Comment by svenstaro** [comment]
Works for me (well with another locale that I actually have). Are you sure the locale is available on your system in its entirety?

Compare with the output of `locale -a`.

**Comment by gusbemacbe** [comment]
> Compare with the output of `locale -a`.

```
C
ca_ES.utf8
de_AT.utf8
de_DE.utf8
el_GR.utf8
en_GB.utf8
en_US.utf8
es_AR.utf8
es_ES.utf8
es_MX.utf8
es_UY.utf8
fr_BE.utf8
fr_CA.utf8
fr_FR.utf8
it_IT.utf8
ja_JP.utf8
ka_GE.utf8
nl_BE.utf8
nl_NL.utf8
POSIX
pt_BR.utf8
pt_PT.utf8
ro_RO.utf8
ru_RU.utf8
uk_UA.utf8
```

**Comment by svenstaro** [comment]
Sorry, I'm not sure what's wrong here for you. I tested this again and it really does work for me. Maybe the way you launch rofi-calc doesn't carry the locale information. For instance, for X11 you might have to set it via your desktop manager (like LightDM).

**Comment by gusbemacbe** [comment]
I found that `pt_BR.UTF-8` shows R$ instead of €. I am sorry! Thank you.
