### ISSUE TITLE
Hide "Add to history"

### ISSUE THREAD

**Issue by kristianvld** [svenstaro/rofi-calc#61]
Hi,

Is there currently a way to hide the "Add to history" entry? Even when running with the "-no-history" option, it only hides the actual history entries, but not the "Add to history" line itself.

Currently running rofi-calc 1.9-1 from arch Community repo.

**Comment by svenstaro** [comment]
The idea is that `-no-history` doesn't load or write the history to disk but you'll still retain the ephemeral history. I take it you want to get rid of the ephemeral history as well and only see the single current live expression?

**Comment by kristianvld** [comment]
Ah I see, that makes sense. Though yes, what I'm looking for is a "clean" version with just the result, maybe this could be added as a separate option?

**Comment by svenstaro** [comment]
Fixed by #63. Will release something with this soon.
