### ISSUE TITLE
Floating point numbers not always returned

### ISSUE THREAD

**Issue by mattlennon3** [svenstaro/rofi-calc#62]
Hey,

When calculating a floating point number such as: `10/3` (output `3.333333333` in qalc)
Nothing is returned to stdout aside from a newline. 

A result that goes to 3dp works:
```
91.34 / 20 = 4.567
```

This is the command I run:
`rofi -show calc -modi calc -no-show-match -no-sort -calc-command 'echo {result}'`

Hope this enough info. Thanks!

**Comment by GladOSkar** [comment]
![image](https://user-images.githubusercontent.com/9497832/98734931-f9598600-23a2-11eb-8796-78a68e0bc315.png)
Works on my machine

**Comment by svenstaro** [comment]
If you want to use this, you should go with `-no-unicode` for the time being as I really don't know how to detect the `≈` properly in C11. :P However, if you want to fix this properly, feel free to take a stab at it. Otherwise, I suppose we could consider this closed.

**Comment by mattlennon3** [comment]
Hey, sorry I have not had much more chance to mess with this. That flag has fixed it for me at least (I get the same output as @GladOSkar at least). Thanks!
