### ISSUE TITLE
Doesn't work with rofi version 1.6.1

### ISSUE THREAD

**Issue by katacarbix** [svenstaro/rofi-calc#65]
When I run `rofi -show calc -modi calc`, rofi says "Mode calc is not found." It stopped working as soon as I upgraded rofi. I also tried rebuilding the newest version of rofi-calc and installing and get the same issue. I am happy to troubleshoot to figure out where things might be going wrong.

**Comment by katacarbix** [comment]
I think it might have something to do with the plugin path it installs to, because when I run `rofi -plugin-path build/.libs -show calc -modi calc` it works just fine.

**Comment by svenstaro** [comment]
I'm running it with rofi 1.6.1 just fine. Sounds like a system issue.

**Comment by katacarbix** [comment]
Oh, I was able to solve the issue by building rofi with meson/ninja rather than make. Sorry for the confusion.

**Comment by svenstaro** [comment]
Sweet to hear you fixed this. :)
