### ISSUE TITLE
[Question] How to see results live while typing

### ISSUE THREAD

**Issue by ivanddm** [svenstaro/rofi-calc#67]
Hi,

Sorry if this might be a stupid question. I haven't been able to to see the results live while typing (in the same way that is shown in the README repo page). I tried switching to different rofi themes but that didn't make a difference.

Is there anything I'm missing?

**Comment by svenstaro** [comment]
It should just work. Can you try starting in the terminal and see whether there are any errors?

**Comment by ivanddm** [comment]
Yes, it does work now, my mistake. I had some hidden bug in my rofi config. Sorry about that!

**Comment by kmehtab** [comment]
@ivanddm can you tell us how do you fix it.

**Comment by ivanddm** [comment]
@kmehtab I don't remember what was causing the problem in my config exactly as I'm not using Linux anymore at the moment. However, this is the config I was using at the end and it was working just fine:

```sh
theme="dmenu"

dir="$HOME/.config/rofi/launcher"

rofi -lines 10 -show calc -modi calc \
     -theme $dir/"$theme" -show-icons -drun-icon-theme "candy-icons" \
     -calc-command "echo -n '{result}' | xclip -selection clipboard" \
     -theme-str '#window { anchor: north; location: north; height: 0; }'
```

Hope that helps!

**Comment by DeeeeLAN** [comment]
To future ticket viewers, make sure your rofi theme has the message box included, some of them hide it for some reason.

**Comment by alma3lol** [comment]
> To future ticket viewers, make sure your rofi theme has the message box included, some of them hide it for some reason.

This solved it for me. Just go to the config file of your theme and look for the keyword children. The one in `mainbox` should contain something like: `[ "listview" ...]`, add "message" to that array and you're good.
![image](https://user-images.githubusercontent.com/46169717/224605885-51f3235c-9d9b-48d4-a59a-3c07d66eb769.png)

**Comment by svenstaro** [comment]
If anyone would like to put a heads-up into the README about this, I'm certainly happy to accept that. :)
