### ISSUE TITLE
Please select interpretation of dots

### ISSUE THREAD

**Issue by GOKOP** [svenstaro/rofi-calc#69]
Since some update to qalc I have to use commas as a decimal separator, because point causes *Please select interpretations of dots (".").* to appear. This is beginning of a message which is an interactive prompt in qalc. I'm not sure how this can be dealt with but right now it makes using rofi-calc very annoying

**Comment by mnn** [comment]
Got exactly same issue. When I use decimal separator on numpad it says `Please select interpretation of dots (".")` and doesn't show a result. I have to use `,` symbol which is _not_ located on numpad which is rather impractical.

Qalculate asks a user just once and the answer is saved. I'll probably stop using rofi-calc until this annoyance is fixed.

**Comment by svenstaro** [comment]
Can you guys maybe ask upstream how to best solve this? Maybe I can set some kind of option at startup but I can't currently find this in the options.

**Comment by mnn** [comment]
With the most recent version of libqalculate and qalculate (aur packages `libqalculate-git` and `qalculate-gtk-git`) and after answering the dot question once (maybe that's not even necessary), rofi-calc is working for me the same way as it used to :smile:.

Possible workarounds are mentioned in [this comment](https://github.com/Qalculate/libqalculate/issues/317#issuecomment-888873360).

**Comment by svenstaro** [comment]
I believe we can consider this fixed. If this remains an issue, please request to reopen. If you'd like to add some useful information about this to the README, I'd encourage you to open a PR to help other users out.
