### ISSUE TITLE
Change input into result when submitting

### ISSUE THREAD

**Issue by agsti** [svenstaro/rofi-calc#70]
First of all sorry if this is documented somewhere or I can use some other tool to achieve said behavior, I have tried a few flags and read the documentation.

I'm looking for a way to change the current input into the result when submitting, a behavior similar to what spotlight on OSX does.

Example: 
Input: 7+4
Press enter (or something else)
current input is 11, and cursor on the right

Thanks, great work btw!

**Comment by GladOSkar** [comment]
If you have `xdotool` installed you could use this, it works great for me:

```bash
rofi -modi calc -show calc -calc-command 'xdotool type --clearmodifiers "{result}"'
```

**Comment by svenstaro** [comment]
That would make a great addition to the examples in the readme if you feel up for it. :)

**Comment by svenstaro** [comment]
@agsti Can we consider this addressed, then?

**Comment by agsti** [comment]
Yeah that's good enough! I'll give it a go, thanks
