### ISSUE TITLE
Segfault when attempting to calculate deteminant

### ISSUE THREAD

**Issue by quantumech3** [svenstaro/rofi-calc#72]
When I run `rofi -modi calc -show calc -calc-command 'xdotool type --clearmodifiers "{result}"'` and attempt to type `det([[1,0],[0,1])`, I get the following error message:
```
** (process:14304): ERROR **: 14:18:50.962: Process errored with: Child process killed by signal 11
[1]    14304 trace trap (core dumped)  rofi -modi calc -show calc -calc-command  -verbose
```

I am using Ubuntu 20.04. I hope the information I provided is useful, but please let me know if you need anything else to solve this problem.

Qalc runs this command fine in the terminal which leads me to believe that this is a problem with rofi-calc.

**Comment by svenstaro** [comment]
Could you try building rofi and qalculate from source running those?

**Comment by quantumech3** [comment]
I will do that, but I think I found the issue. It seems to be a qalc problem actually I was wrong. I traced the problem back to the subprocess spawning that happening periodically when calling qalc and discovered that qalc segfaults when I run `qalc -s update_exchange_rates 1days "det([["`. I think what this means is that I can solve the issue by making rofi-calc only evaluate my expression after I press return.

**Comment by quantumech3** [comment]
I made a pull request with a janky fix for this issue. It will not query qalc if input is either 'det([[' or 'det(['.

**Comment by svenstaro** [comment]
Thanks, but frankly this is the wrong place to fix this behavior in `qalc`. Rather than masking the issue, we should try to get it fixed upstream. A segfault should never occur, after all! Can you contact upstream about this and link the upstream issue report here please?

**Comment by quantumech3** [comment]
Sure I can do that.

**Comment by quantumech3** [comment]
Here is the issue I made https://github.com/Qalculate/libqalculate/issues/324

**Comment by svenstaro** [comment]
Thanks. Just out of interest: Did you try building current qalc from source? Maybe the issue was already resolved upstream.

**Comment by quantumech3** [comment]
> Thanks. Just out of interest: Did you try building current qalc from source? Maybe the issue was already resolved upstream.

No I didnt, turns out that was the problem haha.
