### ISSUE TITLE
Run -calc-command on Enter?

### ISSUE THREAD

**Issue by ryanerwin** [svenstaro/rofi-calc#74]
Is there a way to get the -calc-command to run every time we hit enter?

So instead of <kbd>CTRL</kbd> + <kbd>Enter</kbd> to run `-calc-command`, every time we hit `enter` we would run `-calc-command`?

This way usage would only be <kbd>Enter</kbd> to finalize each line and <kbd>Esc</kbd> when you're all done.

Personally I don't remember to hit <kbd>CTRL</kbd> + <kbd>Enter</kbd>, and this way we've got one less thing to remember.

---

Also, if anyone is having problems getting `calc-command` to interpolate properly, you may need to escape your curly brackets <kbd>{</kbd> <kbd>}</kbd>.

I was trying to get rofi-calc work from [sxhkd](https://github.com/baskerville/sxhkd) and each time "{result}" would fail to be interpolated. I didn't immediately notice that the curly braces were missing...

If you're literally getting "result" on your clipboard instead of your desired calculation output, try escaping both of the curly braces and it should work.

```
XF86Calculator
	rofi -show calc -modi calc -no-show-match -no-sort -calc-command 'echo -n "\{result\}" | xclip -sel clip'
```

**Comment by svenstaro** [comment]
This seems like it would be as simple as rebinding the keys using some CLI flags: `-kb-accept-custom` is defaulting to `Control+Return` but you could just do `-kb-accept-custom Return`. You _may_ need to unbind `-kb-accept-entry` (which also binds just `Return`).

**Comment by svenstaro** [comment]
About your second part: I'd appreciate a PR for the README if you think this would help more people.

**Comment by ryanerwin** [comment]
I suspect the <kbd>{</kbd> <kbd>}</kbd>issue in my case is `zsh` or perhaps some zsh setting. 
I'll try to find the exact factors and then make a PR when I track them down.
Happy to help. This is a great project idea!

As you suspected, I had to unbind `-kb-accept-entry "Control+Return"` to get `custom-entry Return` to work, which isn't a huge improvement for me overalll.

After using Rofi for a few weeks, I hadn't even noticed that rofi will usually let you use <kbd>Control</kbd> + <kbd>Enter</kbd> will let you use the custom entry... I need to figure out how to more easily run shell commands with that. I think using Ctrl + Enter as you did is a great way - I Just need to learn more about how Rofi works.
