### ISSUE TITLE
Support Home & End keys

### ISSUE THREAD

**Issue by rakanalh** [svenstaro/rofi-calc#77]
When trying to calculate something and you end up having to place brackets around certain operations and you want to move the cursor to the beginning:
`1 + 1|`, where `|` is the cursor position. Pressing `HOME` does nothing.
Same goes for `END`.

It would be nice to have support for these keys in rofi-calc.

Thanks.

**Comment by svenstaro** [comment]
You should be able to do this using standard rofi CLI: `-kb-move-front` and `-kb-move-end`.

**Comment by rakanalh** [comment]
Thanks @svenstaro i didn't know these options exist.
