### ISSUE TITLE
Error on `dash`: Cannot set tty process group

### ISSUE THREAD

**Issue by UtkarshVerma** [svenstaro/rofi-calc#81]
I run `rofi` with:
```
rofi -show calc -modi calc -no-show-match -no-sort -theme calc -calc-command "echo -n \"{result}\"|xclip -sel c"
```

but on choosing an expression, I get:
```
/bin/sh: 1: Cannot set tty process group (No such process)
```

The selected result from history is copied to clipboard but the error just pops up. The error isn't there if I don't pipe the output to `xclip`.

**Comment by svenstaro** [comment]
Can't reproduce, I get no errors. What's your environment like?
