### ISSUE TITLE
Mode broken in 1.7.3

### ISSUE THREAD

**Issue by VersusF** [svenstaro/rofi-calc#82]
Hello
After updating to rofi 1.7.3 I get a syntax error as it expects a "(" after the `calc` keyword.
My hypotesis is that `calc` is a reserved word to perform calculations and it is not seen as a mode.

Here is the configuration:
```
configuration {
	show-icons: true;
	icon-theme: "Tela-dark";
	modi: [drun,filebrowser,run,calc];
	combi-modi: [file-browser,drun,calc];
	display-drun: "Run";
	display-calc: "Calc";
	display-run: "Exec";
	display-file-browser: "Explore";
}
@theme "theme.rasi"
```
Let me know if you need additional info.
Thanks a lot!

**Comment by svenstaro** [comment]
Hm weird, I'm currently using rofi 1.7.3 and rofi-calc works without a hitch. I'm not really sure what's wrong here. I even just recompiled rofi-calc against it to verify.

**Comment by svenstaro** [comment]
My config is this:
```
configuration {
    show-icons: true;
    matching: "fuzzy";
    sort: true;
    sorting-method: "fzf";
}
@theme "/usr/share/rofi/themes/gruvbox-dark.rasi"
```
and I start `rofi-calc` using `rofi -show calc -modi calc -no-show-match -no-sort`.

**Comment by VersusF** [comment]
Thanks for the quick reply.
If I specify the modi in the CLI it works as intended. The problem is when I specify the modi in the config file.

I run rofi with `rofi -show drun` so that it takes the modi from the config file. The problem is the file parsing.

A good workaround may be to specify all the modi in the command (usually bound to a keyboard shortcut).
I just wanted to report the "broken configuration file" problem, in case someone else have the modi specified in the rasi configuration file

**Comment by svenstaro** [comment]
Hm, is this perhaps a thing you should bring to the attention of rofi upstream? I'm not sure this should be hacked somewhere in `rofi-calc`.

**Comment by DaveDavenport** [comment]
calc has become a keyword a while back, and recently lists  (for the tabstop) supports distances (that contain the calc keyword). This caused the issue here.

I've added a fix to git that hopefully resolves it (but this makes the parser needs to consider 2 branches until resolved) and I would prefer if it can be tested by more then just me :D

**Comment by SafwanLjd** [comment]
You can just wrap your `modi`s in quotes, i.e.
`modi: ["drun", "filebrowser", "run", "calc"];`

**Comment by svenstaro** [comment]
All in all I think we can stop treating this like an issue in rofi-calc?

**Comment by SafwanLjd** [comment]
@svenstaro I mean... it's not an issue at all if it can be solved by a couple of quotation marks

**Comment by svenstaro** [comment]
Would be great if someone could add a hint on the README or wiki so others don't fall into this. :)

**Comment by DaveDavenport** [comment]
or somebody can confirm the fix I added to git fixes it and I can make a new rofi release?
