### ISSUE TITLE
What to do for long text?

### ISSUE THREAD

**Issue by aryan1932** [svenstaro/rofi-calc#83]
Normally I just give rofi the -keep-right flag to see the end of the line but not working with calc. Here I can't see the second result.

![rofi-2022-02-05-1225-00000](https://user-images.githubusercontent.com/72815172/152632172-35732afc-2f20-4dd6-a4cc-3a855a9dc435.png)

**Comment by svenstaro** [comment]
Frankly not sure. @DaveDavenport could you provide a little input on this one?

**Comment by DaveDavenport** [comment]
Not sure why my feedback is needed? but I can muse:
1. keep-right is a dmenu option (see `man rofi-dmenu`), it does not apply here.
2. Use a less horizontally challenged theme?
3. Use a smaller font
4. Use the `-kb-ellipsize` keybinding to make the other parts of the string visible?

**Comment by aryan1932** [comment]
> 1. keep-right is a dmenu option (see `man rofi-dmenu`), it does not apply here.
 
Yes I figured that later on. 😅

> 4\. Use the `-kb-ellipsize` keybinding to make the other parts of the string visible?

Did not know such a binding existed. Would use it from now on. 👍
For anyone else who might not know about this binding with Alt+period you can toggle between ellipsized modes.
