### ISSUE TITLE
Adding percentage of a number to itself doesn't work as expected

### ISSUE THREAD

**Issue by sathishmanohar** [svenstaro/rofi-calc#89]
In regular calculators when we want to add 50% of number to the number itself we simply do:

10 + 50% which should output 15

However in qalc the output is 10.5 which isn't very intuitive.

![image](https://user-images.githubusercontent.com/270991/188306073-220dfc53-9bba-43e4-bdc9-f6057d2b389e.png)

Currently the expected behaviour can be done with 50 % 10 + 10 which outputs 15 but this isn't the shorthand most users are used to from regular calculators.

**Comment by svenstaro** [comment]
Weird, I'm getting this: 
![image](https://user-images.githubusercontent.com/1664/188306878-53be65db-18bd-4cef-a75f-64d944f46604.png)
This is what you expect to get, right? Might be your system locale or some global qalc setting. What's your qalc version?

**Comment by sathishmanohar** [comment]
Weird. I don't have any other qalc setting. I just installed it. My version is (0.9.10-1)

**Comment by sathishmanohar** [comment]
My machine is Ubuntu 18.04. I didn't get the same behaviour in my 22.04 machine. It works as expected in my Ubuntu 22.04.

**Comment by svenstaro** [comment]
Yeah old Ubuntu versions have ancient versions of qalc. Nothing I can do about that.
