### ISSUE TITLE
Mode calc is not found (Ubuntu)

### ISSUE THREAD

**Issue by matheusfaustino** [svenstaro/rofi-calc#9]
Hi,
Sorry to bother you, but I can't make it work in my machine :/ 
- Ubuntu 18.04
- Rofi 1.5.0

The compilation worked nicely, but when I run `rofi -show calc -modi calc -no-show-match -no-sort` I get this `Mode calc is not found.`

Could you help me :p please

Thanks in advance 

edit: grammar :p

**Comment by svenstaro** [comment]
Where and how did you install rofi-calc itself?

**Comment by matheusfaustino** [comment]
Installed from source

**Comment by svenstaro** [comment]
Are you sure the plugin is in one of rofi's search paths for plugins?

**Comment by matheusfaustino** [comment]
I found the folder on ubuntu. The folder is inside the rofi.pc (which doesn't come with the default installation of rofi from `apt` - you have to install the rofi-dev to get the rofi.pc file with `apt`). 

My plugin's folder is: `/usr/lib/x86_64-linux-gnu/rofi/` 

Thanks for your time @svenstaro
