### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xFedee** [svenstaro/rofi-calc#90]
![image](https://user-images.githubusercontent.com/87451140/193936004-6b738d91-f603-491e-8acd-803e9e4c89f3.png)
how can I change color of calculator result

**Comment by alba4k** [comment]
scemo impara a fare le cose

**Comment by alba4k** [comment]
![immagine](https://github.com/svenstaro/rofi-calc/assets/84153269/8ee1cc24-698d-457f-8b24-bba3d811c329)

**Comment by svenstaro** [comment]
I can't really work with this. Could you try to add a description and a better title? Are you sure this is a rofi-calc problem or just a rofi question?

**Comment by alba4k** [comment]
You can close this as solved (he's a friend of mine, I think we had already solved this months ago)
