### ISSUE TITLE
-calc-command not working with sxhkd

### ISSUE THREAD

**Issue by NotMurPh** [svenstaro/rofi-calc#92]
hey so im running this command on terminal 

`rofi -show calc -modi calc -no-show-match -no-sort -theme calc -no-history -calc-command "echo -n '{expression}' = '{result}' | xclip -sel clip"` 

and it works like a charm and when i hit enter after calculation it copies something like this 

`10 + 50 = 60`

 so everything works well here but here is the issue , when i put this command into my hotkey deamon called sxhkd and i execute it using hotkey the copy part suddenly stops working , so basically when i hit enter after calculation it copies this text instead 
 
`expression = result` 

so for some reason expression and result are not replaced with the real expression or result 
i will be really happy if you could help me on this , oh btw thanks for the project :)

**Comment by Arian8j2** [comment]
see https://github.com/svenstaro/rofi-calc/issues/76
