### ISSUE TITLE
No calculations in combi mode

### ISSUE THREAD

**Issue by JaCoB1123** [svenstaro/rofi-calc#95]
I'm not sure if that's by-design, but I'm having trouble getting calc to work in combi mode. With the following call

```
rofi -show combi -combi-modi window,run,calc
```

I get window and run functionality as expected but no matter what expressions I input, they are not calculated. I only get one line saying "calc Add to history".

**Comment by svenstaro** [comment]
Yeah I think this can't be done. I've investigated this before and I think it's not possible in Combi mode.

**Comment by JaCoB1123** [comment]
Okay, that's too bad. I really enjoyed having everything available with Wox on Windows. Thanks anyways..

**Comment by svenstaro** [comment]
I think that's pushing rofi a bit too far. rofi-calc is abusing it a bit already. ;)
