### ISSUE TITLE
intense use of CPU

### ISSUE THREAD

**Issue by carmelopellegrino** [svenstaro/rofi-calc#96]
Hi,

I've noticed that rofi-calc uses a lot of CPU when there is no user input after a first evaluation has been performed.
I think the problem is that it repeatedly calls the `calc_preprocess_input` function, even if there is no new input.

This behaviour has been tested only on Arch Linux, I don't know of other affected distros.

As a solution for this behaviour, I've forked the project and made [this commit](https://github.com/svenstaro/rofi-calc/compare/master...carmelopellegrino:rofi-calc:master), although I don't really know if it's the best solution. For example, I tried using the `sw->cmd` field with similar results, but I'm not sure of any possible corner case that could break the code somewhere else.

I can start a pull request, if desired.

**Comment by svenstaro** [comment]
I think that's a fine idea. I also just now noticed this behavior. I like your general solution, just make sure to remove the debug and slap some comments onto it so we know what it's for without reading the code.

**Comment by svenstaro** [comment]
Nevermind, looks like this is actually solved in #66. I just haven't given this project love in some time. I'll merge that instead.

**Comment by svenstaro** [comment]
I merged it, please see whether it works for you. I'll then cut a release.

**Comment by svenstaro** [comment]
Actually there was a memory leak in #66 and the fixed version looks a lot like yours. :D

**Comment by carmelopellegrino** [comment]
Hi @svenstaro, sorry for having disappeared! Thank you for the fix!
