### ISSUE TITLE
Couldn't open directory 'm4'

### ISSUE THREAD

**Issue by Seres67** [svenstaro/rofi-calc#99]
`autoreconf -i` spits out this error `aclocal: warning: couldn't open directory 'm4': No such file or directory`, failing to configure the project and eventually the build process. I found out that creating the 'm4' folder solves the issue, and the building process succeeds.

**Comment by Seres67** [comment]
PR #100 adds `mkdir m4` in the README instructions

**Comment by svenstaro** [comment]
This is odd since it shouldn't really be required. It seems to work for me. I think another user reported this as well. I wonder what the core problem is. Other than autotools just being autotools.

**Comment by Seres67** [comment]
#98 reported the same issue I believe, though they are also missing libtool tool AFAIK. We are both on Fedora, maybe Fedora and autotools don't go along too much?

**Comment by svenstaro** [comment]
Should be fixed by #101.
